---
title: "PVAR_est"
author: "J Coetsee - 19491050"
date: "01/06/2021"
output: pdf_document
---

### PVAR estimation 

# packages and data
```{r}

library(pacman)
p_load("scales", "panelvar", "plm", "tseries", "vars", "gridExtra", "tictoc", "parallel", "tidyverse")
source("code/growth_fun.R")
theme_set(theme_light())

#setting memory limits (atm limit.size = 311.61)

memory.limit(size=50000)


# reading in data

pvar_data <- read.csv("C:/Projects/Time_Series/PVAR_19491050/data/joined.csv")

#growth rates for gini and pc income:

pvar_data <- pvar_data %>% 
  group_by(State) %>% 
  mutate( Inc_growth = c(NA,diff(realpc_income))/lag(realpc_income, 1), 
          Gini_growth = c(NA,diff(Gini))/lag(Gini, 1)) %>% slice(-1) %>% 
    mutate(Year = ordered(Year),
           st = as_factor(st)) %>% 
  ungroup() %>% 
  select(Year, st, Inc_growth, Gini_growth)

# must be in data.frame format, not tibble. I struggled with this for long
pvar_data <- as.data.frame(pvar_data)
```

# Baseline PVAR estimation - full sample 1930-2018

```{r}
#Baseline with 

baseline <- pvargmm(dependent_vars = c("Inc_growth", "Gini_growth"),
                             lags = 4,
                             transformation = "fod",
                             data = pvar_data,
                             panel_identifier=c("st", "Year"),
                             steps = c("twostep"),
                             system_instruments = FALSE,
                             max_instr_dependent_vars = 99,
                             max_instr_predet_vars = 99,
                             min_instr_dependent_vars = 2L,
                             min_instr_predet_vars = 1L,
                             collapse = TRUE
)

summary(baseline)

#IRFs

pvar_irf <- oirf(baseline, n.ahead = 20)

plot(pvar_irf)


#IRF's confidence bands: 

tic()
pvar_conf <- bootstrap_irf(baseline,
  typeof_irf = "OIRF",
  n.ahead = 20,
  nof_Nstar_draws = 10,
  confidence.band = 0.95)
toc()

plot(pvar_irf, pvar_conf)

##### Cumulative IRFs:

## manually for income: ## 
#vector of IRF for income and income
inc_inc <- c(5.072704e-02, 1.098332e-02, 9.392457e-03, 6.394237e-04, -6.217209e-03, -3.935836e-03, -2.344428e-03, -2.990627e-04,8.811658e-04, 9.751956e-04, 6.016479e-04, 1.495974e-04,-1.217544e-04, -2.059990e-04,-1.485041e-04, -5.419102e-05, 1.220126e-05, 4.004328e-05, 3.470943e-05, 1.640435e-05)
#vector of IRF for income and growth
inc_gr <- c(5.109329e-05,-2.069661e-04 ,2.874334e-03 ,2.191037e-03 ,3.081370e-03 ,1.818792e-04 ,-5.204909e-04 ,-6.059566e-04 ,4.214899e-04 ,1.069992e-04 ,9.729479e-05 , 1.074632e-04 ,-3.099483e-05 ,-3.759734e-05 ,-2.555751e-05 ,-1.956363e-05 ,-1.179556e-06 ,7.410495e-06 , 6.584319e-06,4.256369e-06 )
# Time period after shock
Year <- c(1:20)

# concatenating in a df:
pvar_irf_cum_inc <- data.frame(inc_inc, inc_gr, Year)

#plot:
pvar_irf_cum_inc %>% 
  mutate(cumul_inc = cumsum(inc_inc)) %>% 
  ggplot() +
  geom_line(aes(x = Year, y = cumul_inc)) +
  labs(title = "Income Response to Income Shock",
       y = "") +
  scale_y_continuous(labels = percent)

pvar_irf_cum_inc %>% 
  mutate(cumul_gr = cumsum(inc_gr)) %>% 
  ggplot() +
  geom_line(aes(x = Year, y = cumul_gr)) + 
  labs(title = "Gini Response to Income Shock",
       y = "") +
  scale_y_continuous(labels = percent)

  ## For Growth: ##

#vector of IRF for Growth and income
gr_inc <- c(0.000000e+00, -4.143564e-03, -1.162255e-02, -6.739416e-03,-1.955385e-03 , 1.345689e-04,1.942735e-03 ,1.656778e-03, 6.767415e-04,  6.031671e-05, -3.247110e-04,  -3.649290e-04, -1.986487e-04, -4.267119e-05, 5.078826e-05, 7.553122e-05,5.132632e-05, 1.700295e-05,-6.297061e-06, -1.489977e-05)
#vector of IRF for Growth and growth
gr_gr <- c(3.392918e-02 ,-7.216043e-03 ,-3.633772e-03 ,2.578326e-03 ,-2.325317e-03 , -3.281926e-04,9.607700e-04 ,2.097168e-05 ,1.632232e-04 ,1.668564e-04 ,-1.095603e-04 ,-6.853123e-05 ,-2.744108e-05 ,-3.081116e-05 ,6.728784e-06 ,1.689650e-05 ,8.821304e-06 ,5.870646e-06 ,5.064842e-07 ,-2.960363e-06 )

# concatenating in a df:
pvar_irf_cum_gr <- data.frame(gr_inc, gr_gr, Year)

#plot: # seems like gini bottom right (but different y axis values)

pvar_irf_cum_gr %>% 
  mutate(cumul_inc = cumsum(gr_gr)) %>% 
  ggplot() +
  geom_line(aes(x = Year, y = cumul_inc)) +
  labs(title = "Gini Response to Gini Shock",
       y = "") +
  scale_y_continuous(labels = percent)


# plot: seems like income top right, same y axis values
pvar_irf_cum_inc %>% 
  mutate(cumul_gr = cumsum(gr_inc)) %>% 
  ggplot() +
  geom_line(aes(x = Year, y = cumul_gr)) +
  labs(title = "Income Response to Gini Shock",
       y = "") +
  scale_y_continuous(labels = percent)


#so these 4 are good. But I also need the bootstrapped confidence intervals:

```


```{r}
# fevd:

fevd_baseline <- fevd_orthogonal(baseline, n.ahead = 20)

plot(fevd_baseline$Gini_growth)

```

Counterfactual, period without 2005:2018: This is the replication study.

```{r}

pvar_19302005 <- pvar_data %>% 
  filter(Year %in% c(1930:2005))

model19302005 <- pvargmm(dependent_vars = c("Inc_growth", "Gini_growth"),
                             lags = 4,
                             transformation = "fod",
                             data = pvar_19302005,
                             panel_identifier=c("st", "Year"),
                             steps = c("twostep"),
                             system_instruments = FALSE,
                             max_instr_dependent_vars = 99,
                             max_instr_predet_vars = 99,
                             min_instr_dependent_vars = 2L,
                             min_instr_predet_vars = 1L,
                             collapse = TRUE
)

summary(model19302005)

#IRFs

pvar_irf_19302005 <- oirf(model19302005, n.ahead = 20)

plot(pvar_irf_19302005)


#IRF's confidence bands: 

pvar_conf_19302005 <- bootstrap_irf(model19302005,
  typeof_irf = "OIRF",
  n.ahead = 20,
  nof_Nstar_draws = 10,
  confidence.band = 0.95)

plot(pvar_irf_19302005, pvar_conf_19302005)

# fevd:

fevd_19302005 <- fevd_orthogonal(model19302005, n.ahead = 20)

plot(fevd_19302005$Gini_growth)

```


Only Small dataset

```{r}
### trying with a smaller dataset: just the new data 2005:2018

pvar_small <- pvar_data %>% 
  group_by(st) %>% 
  filter(Year %in% c("2005":"2018"))
 
# as df:

pvar_small <- as.data.frame(pvar_small)

# running var model:

test_small <- pvargmm(dependent_vars = c("Gini_growth", "Inc_growth"),
                             lags = 4,
                             transformation = "fod",
                             data = pvar_small,
                             panel_identifier=c("st", "Year"),
                             steps = c("twostep"),
                             system_instruments = FALSE,
                             max_instr_dependent_vars = 99,
                             max_instr_predet_vars = 99,
                             min_instr_dependent_vars = 2L,
                             min_instr_predet_vars = 1L,
                             collapse = FALSE
)

summary(test_small)

# IRF's:

pvar_small_irf <- oirf(test_small, n.ahead = 12)

plot(pvar_small_irf)

#girf:

pvar_girf <- girf(test_small, n.ahead = 12,ma_approx_steps = 13 )
plot(pvar_girf)



# Confidence intervals:

pvar_small_conf <- bootstrap_irf(test_small,
  typeof_irf = "OIRF",
  n.ahead = 12,
  nof_Nstar_draws = 50,
  confidence.band = 0.95)

plot(pvar_small_irf, pvar_small_conf)

#fevd_small dataset;

fevd_small <- fevd_orthogonal(test_small, n.ahead = 12)
plot(fevd_small$Inc_growth)

fevd_small_df <- as.data.frame(fevd_small) %>% 
  mutate(year = round(1:12)) %>% 
  gather(Measure, value = Value, Gini_growth.Gini_growth:Inc_growth.Inc_growth)


#fevd income plot:

income_fevd <- fevd_small_df %>% 
  group_by(Measure) %>% 
  filter(Measure == c("Inc_growth.Inc_growth", "Inc_growth.Gini_growth")) %>% 
  ggplot()+
  geom_line(aes(y = Value, x = year, colour = Measure)) +
  labs(title = "Income Growth",
       y = "",
       x = "Years") +
  theme(legend.position = "none") +
  scale_x_continuous(breaks =seq(1,12, by = 1)) +
  scale_y_continuous(labels = percent)


#fevd Gini plot:

gini_fevd <- fevd_small_df %>% 
  group_by(Measure) %>% 
  filter(Measure == c("Gini_growth.Gini_growth", "Gini_growth.Inc_growth")) %>% 
  ggplot()+
  geom_line(aes(y = Value, x = year, colour = Measure)) +
  labs(title = "Gini Growth",
       y = "",
       x = "Years") +
  theme(legend.position = "none")+
  scale_x_continuous(breaks =seq(1,12, by = 1)) +
  scale_y_continuous(labels = percent)


fevd_plot <- grid.arrange(income_fevd, gini_fevd, nrow = 1,
                          bottom = "Income in Blue and Gini in Red")

```


### Regional PVARs

1 = 
2 = 
3 = 
4 = 
5 = 
6 = 
7 = 
8 = 

```{r}
#reading in income data:

regional <- read.csv("C:/Projects/Time_Series/PVAR_19491050/data/joined.csv")



```





















example:

```{r}
## Not run:
library(panelvar)
data(abdata)

#it works for both the dataset without the matrix of years. Both deliver the same results. 

ex3_abdata <-pvargmm(
    dependent_vars = c("emp"),
    lags = 4,
    predet_vars = c("wage"),
    exog_vars = c("cap"),
    transformation = "fd",
    data = abdata,
    panel_identifier = c("id", "year"),
    steps = c("twostep"),
    system_instruments = TRUE,
    max_instr_dependent_vars = 99,
    max_instr_predet_vars = 99,
    min_instr_dependent_vars = 2L,
    min_instr_predet_vars = 1L,
    collapse = FALSE
)
## End(Not run)
summary(ex3_abdata)


### OR

data("Dahlberg")
## Not run: 
ex1_dahlberg_data <- pvargmm(dependent_vars = c("expenditures", "revenues", "grants"),
                             lags = 1,
                             transformation = "fod",
                             data = Dahlberg,
                             panel_identifier=c("id", "year"),
                             steps = c("twostep"),
                             system_instruments = FALSE,
                             max_instr_dependent_vars = 99,
                             max_instr_predet_vars = 99,
                             min_instr_dependent_vars = 2L,
                             min_instr_predet_vars = 1L,
                             collapse = FALSE
)

summary(ex1_dahlberg_data)

#IRF's of example:

example_irf <- oirf(ex1_dahlberg_data, n.ahead = 12)

plot(example_irf)

bootstrap <- bootstrap_irf(ex1_dahlberg_data,
  typeof_irf = "OIRF",
  n.ahead = 12,
  nof_Nstar_draws = 2,
  confidence.band = 0.95)

plot(example_irf, bootstrap)

#fevd:

data("ex1_dahlberg_data")
example_fevd <- fevd_orthogonal(ex1_dahlberg_data, n.ahead = 12)

plot(example_fevd$expenditures)


```

# baseline with system instruments = TRUE

```{r}
baselineGMM <- pvargmm(dependent_vars = c("Inc_growth", "Gini_growth"),
                             lags = 4,
                             transformation = "fod",
                             data = pvar_data,
                             panel_identifier=c("st", "Year"),
                             steps = c("twostep"),
                             system_instruments = TRUE,
                             max_instr_dependent_vars = 99,
                             max_instr_predet_vars = 99,
                             min_instr_dependent_vars = 2L,
                             min_instr_predet_vars = 1L,
                             collapse = TRUE
)

summary(baselineGMM)

#IRFs

pvargmm_irf <- oirf(baselineGMM, n.ahead = 12)

plot(pvargmm_irf)


```

