---
# IMPORTANT: Change settings here, but DO NOT change the spacing.
# Remove comments and add values where applicable.
# The descriptions below should be self-explanatory

title: "Revisiting 'Income inequality and economic growth: a panel VAR approach'"
subtitle: "June 2021 - Econometrics 871"

documentclass: "elsarticle"

# --------- Thesis title (Optional - set to FALSE by default).
# You can move the details below around as you please.
Thesis_FP: FALSE
# Entry1: "An unbelievable study with a title spanning multiple lines."
# Entry2: "\\textbf{Nico Katzke}" # textbf for bold
# Entry3: "A thesis submitted toward the degree of Doctor of Philosophy"
# Uni_Logo: Tex/Logo.png # Place a logo in the indicated location (from your root, e.g. defaults to ~/Tex/Logo.png) and uncomment this line. Leave uncommented for no image
# Logo_width: 0.3 # If using a logo - use this to set width (size) of image
# Entry4: "Under the supervision of: \\vfill Prof. Joe Smith and Dr. Frank Smith"
# Entry5: "Stellenbosch University"
# Entry6: April 2020
# Entry7:
# Entry8:

# --------- Front Page
# Comment: ----- Follow this pattern for up to 5 authors
AddTitle: TRUE # Use FALSE when submitting to peer reviewed platform. This will remove author names.
Author1: "Johannes Coetsee - 19491050"  # First Author - note the thanks message displayed as an italic footnote of first page.
Ref1: "Stellenbosch University" # First Author's Affiliation
Email1: "19491050\\@sun.ac.za" # First Author's Email address

keywords: "Panel vector autoregression \\sep Income Inequality \\sep Economic Growth " # Use \\sep to separate
#JELCodes: "L250 \\sep L100"

# ----- Manage headers and footers:
#BottomLFooter: $Title$
#BottomCFooter:
#TopLHeader: \leftmark # Adds section name at topleft. Remove comment to add it.
BottomRFooter: "\\footnotesize Page \\thepage" # Add a '#' before this line to remove footer.
addtoprule: TRUE
addfootrule: TRUE               # Use if footers added. Add '#' to remove line.

# --------- page margins:
margin: 2.3 # Sides
bottom: 2 # bottom
top: 2.5 # Top
HardSet_layout: TRUE # Hard-set the spacing of words in your document. This will stop LaTeX squashing text to fit on pages, e.g.
# This is done by hard-setting the spacing dimensions. Set to FALSE if you want LaTeX to optimize this for your paper.

# --------- Line numbers
linenumbers: FALSE # Used when submitting to journal

# ---------- References settings:
# You can download cls format here: https://www.zotero.org/ - simply search for your institution. You can also edit and save cls formats here: https://editor.citationstyles.org/about/
# Hit download, store it in Tex/ folder, and change reference below - easy.
bibliography: Tex/ref.bib       # Do not edit: Keep this naming convention and location.
csl: Tex/harvard-stellenbosch-university.csl # referencing format used.

# ---------- General:
RemovePreprintSubmittedTo: TRUE  # Removes the 'preprint submitted to...' at bottom of titlepage
Journal: "Time Series Econometrics 871"   # Journal that the paper will be submitting to, if RemovePreprintSubmittedTo is set to TRUE.
toc: FALSE                       # Add a table of contents
numbersections: TRUE             # Should sections (and thus figures and tables) be numbered?
fontsize: 11pt                  # Set fontsize
linestretch: 1.2                # Set distance between lines.
link-citations: TRUE            # This creates dynamic links to the papers in reference list.

### Adding additional latex packages:
# header-includes:
#    - \usepackage{colortbl} # Add additional packages here.

output:
  pdf_document:
    keep_tex: TRUE
    template: Tex/TexDefault.txt
    fig_width: 3.5 # Adjust default figure sizes. This can also be done in the chunks of the text.
    fig_height: 3.5
abstract: |
  This paper attempts to replicate and critique @atems, in which the authors attempt to model the contemporaneous effects of income inequality and economic growth of the United States at the state level, using a Panel Vector Autoregression (PVAR) approach. 
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
# Note: Include = FALSE implies the code is executed, but not printed in your pdf.
# warning and message = FALSE implies ugly messages and warnings are removed from your pdf.
# These should be picked up when you execute the command chunks (code sections below) in your rmd, not printed in your paper!

```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

# Introduction \label{Introduction}

This paper attempts to replicate the paper by @atems. It will specifically emphasise the methodological approach used by these authors in an attempt to uncover whether their PVAR approach holds against checks for robustness. 

The paper will be structured in the following manner: for completeness, a overview of the primary differences between the PVAR and VAR approaches will be given, after which the contribution of @atems will be discussed. Section \ref{Section 2.2} looks at their methodological approach through a critical lens, thereby also informing which robustness checks are considered the important to include in the current analysis.

# Section 2 \label{Section 2}

## Panel Vector Autoregression \label{Section 2.1}

Panel Vector Autoregressions are, as the name indicates, a variation of the standard VAR approach applied to panel datasets. Whereas VAR's treat all variables in a given system as endogenous, the PVAR approach also allows for unobserved individual heterogeneity. As panel data is comprised out of various cross-sectional units of observation - in our case, states - a VAR approach to model interactions between endogenous variables need to account for the fact that the underlying structure might differ across these units. A PVAR approach therefore imposes an additional restriction, namely, that the underlying structure is the same for all of the units of analysis. However, @love notes that this restriction is highly likely to be violated in practice. In order to overcome this additional restriction on the parameter, @love suggest the introduction of fixed effects, thereby allowing for individual heterogeneity in the levels of the variables. Crucially, these fixed effects are correlated with the regressors because of the necessary inclusion of dependent variable lags in the model (the 'autoregressive' aspect of VARs), meaning that mean-differencing - the standard method used to eliminate fixed effects - will bias the regression coefficients. To solve this problem, @arellano advocate for the usage of the ‘Helmert procedure’, where the means of only the future observations for each unit is removed. This procedure therefore transforms the variables in a way that preserves the orthogonality between the variables and the lagged regressors, which, in turn, allows for the usage of the lagged regressors as instruments whereby the coefficients of the systems can be estimated. Moreover, these orthogonal relationships provide the necessary moment conditions that allow for VAR estimation using Generalized Method of Moments (GMM). 




## Inequality and Economic Growth [@atems] \label{Section 2.2}


a new comprehensive panel of annual U.S. state-level income
inequality data from 1930 to 2005 constructed by Frank (2009b), this study reconsiders
the relationship between inequality and per capita income using a panel VAR
approach. A panel VAR allows not only for the examination of the correlation between
income inequality and per capita income, but also the dynamic responses of these variables
to income and inequality shocks, as well.

### Methodology {-}


### Data {-}
There are three datasets used by @atems that are relevant for our discussion. The first, data on state-level economic growth, is measured by the annual change in per capita real income for the 48 contiguous US states (listed in the Appendix) for the period 1930-2005. 

@atems uses a panel of state-level income inequality data (sourced by @frank), for the period 1930-2005 for the United States. Their measure of inequality, the Gini coefficient, is constructed using tax filing data. The usage of tax data is often considered problematic in that it excludes low-income earners, thereby introducing possibly misleading results. 


overview of the data as a prelude to the estimation
of the structural VAR. Our dataset consists of annual data on the percentage
change in per capita real income and various income inequality measures for the 48

### Results {-}


# Section 3 \label{Section 3 }


# Conclusion


\newpage

# References {-}

<div id="refs"></div>


# Appendix {-}

* Table of 48 states and the state sample splits


