---
title: "README"
author: "J Coetsee - 19491050"
date: "25/05/2021"
output: pdf_document
---

## Purpose

This README discusses my Time Series Econometrics project for the Advanced Econometrics 871 Course in 2021. It is due on the 7th of June. The goal of this project is to replicate and critique the PVAR paper titled "Income inequality and economic growth: a panel VAR approach" by Bebonchu Atems & Jason Jones (included in the bin folder). 

# Setting chunk options, loading packages:


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

library(pacman)
p_load("tidyverse", "panelvar", "scales")
```



Here are the documents that encompass this project:

* PVAR_19491050.Rmd - the 'Texevier' Write_Up file based on Nico Katzke's package and template. This is the file that knits the final document

* PVAR_19491050.pdf - the final document to be submitted.

* Wrangling.rmd - imports the data, makes it into a format that can be compatible with both the 'tidyverse' and the 'panelvar' package, and makes descriptive statistics. In essence, this document sets up the data to be converted into the model.

* Model.rmd - uses the 'panelvar' package to model the VAR using the data exported by wrangling.rmd. This document also plots the relevant IRF's. 


## Approach

* Introduction

* Distinction between VAR and PVAR

* Discussion of Methodology of Atems and Jones (2015)

- Data

- Methodology

- Critique

* Replication of Methodology

- Descriptive statistics

- Baseline model

* Robustness checks

- Different State subsets (which drive the results?)

- Structural Breaks (they have three, does it make sense to extend?)

* Results (is their approach robust?)





